### ISSUE TITLE
Appends new lines if a variable is passed to message

### ISSUE THREAD

**Issue by v1rtl** [superjojo140/ascii-bar#1]
I have the following code:

```js
const bar = new AsciiBar({
    total: 3,
    formatString: '#spinner #bar #message',
    hideCursor: false,
    enableSpinner: true,
    width: process.stdout.columns - 30,
  })

const account = { address: '0x...' }
bar?.update(total++, `🧑‍🍳 Preparing transaction for ${account.address}`)
```

And the whole progress bar gets messed up:

![image](https://github.com/superjojo140/ascii-bar/assets/35937217/5633f427-ee04-40ad-adce-e58fe3ba1a27)

**Comment by superjojo140** [comment]
You set the width of the **#bar** part to `process.stdout.columns - 30`
If the message behind the bar (`🧑‍🍳 Preparing transaction for ${account.address}`) is longer than 30 characters the whole rendered progress bar will be longer than a single terminal line. This will cause some crazy display hazards.

So use a smaller value for the **width** parameter (e.g. `20 `or `process.stdout.columns - 60`) when initialising the progressbar. Good luck!
